### ISSUE TITLE
ExpandedType package - Could not expand union/intesection type

### ISSUE THREAD

**Issue by arieffikhrie** [break-stuff/cem-tools#18]
The `expandedType` properties does not get the final inferred type.

eg
```ts
type Size = 'small' | 'medium' | 'large';
type ChildSize =  Size | 'extra-small';
```
the ChildSize expandedType properties will output ` | 'extra-small'`
expecting it to be `'small' | 'medium' | 'large' | 'extra-small'`

While doing intersecting, it would never show `expandedType` property.

```ts
type Size = 'small' | 'medium' | 'large';
type ChildSize =  Size & ('small' | 'medium' | 'extra-large');
```

Can use this Lit Component to replicate

```ts
import { html, LitElement } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';

/** The Size references. */
type Size = 'small' | 'medium' | 'large';

/** The Child Size references. */
type ChildSize =  Size | 'extra-small';

/**
 * The test element.
 * 
 * @example
 * ```html
 * <my-test size="small" child-size="extra-small">Content</my-test>
 * ```
 * 
 * @slot Default slot
 */
@customElement('my-test')
export class Test extends LitElement {
  /** The size. */
  @property() size?: Size = 'medium';

  /** The child size. */
  @property({attribute: 'child-size'}) childSize: ChildSize = 'extra-small';

  render() {
    return html`<div class=${classMap({
      test: true,
      [`test--${this.size}`]: true
    })}>
      <div class=${classMap({
        'test__child': true,
        [`test__child--${this.childSize}`]: true
      })}><slot></slot></div>
    </div>`
  }
}
```

Output custom-elements.json

```json
{
  "schemaVersion": "1.0.0",
  "readme": "",
  "modules": [
    {
      "kind": "javascript-module",
      "path": "src/Test.ts",
      "declarations": [
        {
          "kind": "class",
          "description": "The test element.",
          "name": "Test",
          "slots": [
            {
              "description": "slot",
              "name": "Default"
            }
          ],
          "members": [
            {
              "kind": "field",
              "name": "size",
              "type": {
                "text": "Size | undefined"
              },
              "default": "'medium'",
              "description": "The size.",
              "attribute": "size",
              "expandedType": {
                "text": "'small' | 'medium' | 'large' | undefined"
              }
            },
            {
              "kind": "field",
              "name": "childSize",
              "type": {
                "text": "ChildSize"
              },
              "default": "'extra-small'",
              "description": "The child size.",
              "attribute": "child-size",
              "expandedType": {
                "text": " | 'extra-small'"
              }
            }
          ],
          "attributes": [
            {
              "name": "size",
              "type": {
                "text": "Size | undefined"
              },
              "default": "'medium'",
              "description": "The size.",
              "fieldName": "size",
              "expandedType": {
                "text": "'small' | 'medium' | 'large' | undefined"
              }
            },
            {
              "name": "child-size",
              "type": {
                "text": "ChildSize"
              },
              "default": "'extra-small'",
              "description": "The child size.",
              "fieldName": "childSize",
              "expandedType": {
                "text": " | 'extra-small'"
              }
            }
          ],
          "superclass": {
            "name": "LitElement",
            "package": "lit"
          },
          "tagName": "my-test",
          "customElement": true
        }
      ],
      "exports": [
        {
          "kind": "js",
          "name": "Test",
          "declaration": {
            "name": "Test",
            "module": "src/Test.ts"
          }
        },
        {
          "kind": "custom-element-definition",
          "name": "my-test",
          "declaration": {
            "name": "Test",
            "module": "src/Test.ts"
          }
        }
      ]
    }
  ]
}
```

**Comment by break-stuff** [comment]
Thank you for the great repro. Let me dig into it.

**Comment by break-stuff** [comment]
@arieffikhrie, I think I found the issue. I just deployed 1.1.2 (#27) and I think that should fix your issue. Let me know if you run into any issues.

**Comment by arieffikhrie** [comment]
Thanks @break-stuff ,

Just tested it and it worked for this use case.

but now it created error when doing something like this `type Test = 'test' | null;`

error 
```bash
file:///cem-tools-test/node_modules/@custom-elements-manifest/analyzer/src/utils/index.js:67
    throw new Error(`\n\n[${name ?? 'unnamed-plugin'}]: ${errorMessage}\n\n ${e.stack}\n`);
          ^

Error: 

[expand-types-plugin]: Looks like you've hit an error in third party plugin: expand-types-plugin. Please try to create a minimal reproduction and inform the author of the expand-types-plugin plugin.

 TypeError: Cannot read properties of undefined (reading 'escapedText')
    at file:///cem-tools-test/node_modules/cem-plugin-expanded-types/dist/index.js:100:62
    at Array.map (<anonymous>)
    at setBasicUnionTypes (file:///cem-tools-test/node_modules/cem-plugin-expanded-types/dist/index.js:96:121)
    at parseFileTypes (file:///cem-tools-test/node_modules/cem-plugin-expanded-types/dist/index.js:78:7)
    at collectPhase (file:///cem-tools-test/node_modules/cem-plugin-expanded-types/dist/index.js:64:3)
    at file:///cem-tools-test/node_modules/@custom-elements-manifest/analyzer/src/create.js:91:23
    at withErrorHandling (file:///cem-tools-test/node_modules/@custom-elements-manifest/analyzer/src/utils/index.js:58:5)
    at file:///cem-tools-test/node_modules/@custom-elements-manifest/analyzer/src/create.js:90:7
    at Array.forEach (<anonymous>)
    at visitNode (file:///cem-tools-test/node_modules/@custom-elements-manifest/analyzer/src/create.js:89:19)

    at withErrorHandling (file:///cem-tools-test/node_modules/@custom-elements-manifest/analyzer/src/utils/index.js:67:11)
    at file:///cem-tools-test/node_modules/@custom-elements-manifest/analyzer/src/create.js:90:7
    at Array.forEach (<anonymous>)
    at visitNode (file:///cem-tools-test/node_modules/@custom-elements-manifest/analyzer/src/create.js:89:19)
    at visitNodes (/cem-tools-test/node_modules/typescript/lib/typescript.js:29004:30)
    at Object.forEachChild (/cem-tools-test/node_modules/typescript/lib/typescript.js:29243:24)
    at visitNode (file:///cem-tools-test/node_modules/@custom-elements-manifest/analyzer/src/create.js:95:8)
    at collect (file:///cem-tools-test/node_modules/@custom-elements-manifest/analyzer/src/create.js:86:3)
    at file:///cem-tools-test/node_modules/@custom-elements-manifest/analyzer/src/create.js:33:5
    at Array.forEach (<anonymous>)

Node.js v18.17.1
```

**Comment by break-stuff** [comment]
Ah, what version are you on? I think I just pushed out a version yesterday afternoon that fixed this.

**Comment by arieffikhrie** [comment]
Im using this version 1.1.2 that you mention

**Comment by break-stuff** [comment]
I'm sorry. It looks like I haven't deployed 1.1.3 yet. Deploying it now.

**Comment by arieffikhrie** [comment]
Hi @break-stuff , thanks for updating the fix, there is no error now when running CEM tools.

Currently expanded type for `type Test = 'test' | null;` is `{"text": "'test' | "}`.

**Comment by break-stuff** [comment]
That's strange. I'm not sure why TypeScript is resolving it that way. If you use `undefined` instead of `null`, does it resolve correctly?

**Comment by arieffikhrie** [comment]
Nope, using both undefined and null going to show empty string.

i test with this code

```ts
import { html, LitElement } from "lit";
import { customElement } from "lit/decorators.js";

/** Type 1 references. */
type Type1 = "foo" | "bar" | "baz";

/** Type 2 references. */
type Type2 = Type1 | undefined;

/** Type 3 references. */
type Type3 = Type1 | null;

/**
 * The test element.
 *
 * @example
 * ```html
 * <my-test>Content</my-test>
 * ```
 *
 * @slot Default slot
 */
@customElement("my-test")
export class Test extends LitElement {
  /** Value 1 References. */
  private value1: Type1 = "foo";

  /** Value 2 References. */
  private value2?: Type1 = "bar";

  /** Value 3 References. */
  private value3: Type2 = undefined;

  /** Value 4 References. */
  private value4: Type3 = null;

  /** Value 5 References. */
  private value5?: Type2;

  render() {
    return html`<div>
      <slot>FooBarBaz</slot>
      <div>
        <ul>
          <li>${this.value1}</li>
          <li>${this.value2}</li>
          <li>${this.value3}</li>
          <li>${this.value4}</li>
          <li>${this.value5}</li>
        </ul>
      </div>
    </div>`;
  }
}
```

This is the output
```json
{
  "schemaVersion": "1.0.0",
  "readme": "",
  "modules": [
    {
      "kind": "javascript-module",
      "path": "src/Test.ts",
      "declarations": [
        {
          "kind": "class",
          "description": "The test element.",
          "name": "Test",
          "slots": [
            {
              "description": "slot",
              "name": "Default"
            }
          ],
          "members": [
            {
              "kind": "field",
              "name": "value1",
              "type": {
                "text": "Type1"
              },
              "privacy": "private",
              "default": "\"foo\"",
              "description": "Value 1 References.",
              "expandedType": {
                "text": "'foo' | 'bar' | 'baz'"
              }
            },
            {
              "kind": "field",
              "name": "value2",
              "type": {
                "text": "Type1 | undefined"
              },
              "privacy": "private",
              "default": "\"bar\"",
              "description": "Value 2 References.",
              "expandedType": {
                "text": "'foo' | 'bar' | 'baz' | undefined"
              }
            },
            {
              "kind": "field",
              "name": "value3",
              "type": {
                "text": "Type2"
              },
              "privacy": "private",
              "default": "undefined",
              "description": "Value 3 References.",
              "expandedType": {
                "text": "'foo' | 'bar' | 'baz' | "
              }
            },
            {
              "kind": "field",
              "name": "value4",
              "type": {
                "text": "Type3"
              },
              "privacy": "private",
              "default": "null",
              "description": "Value 4 References.",
              "expandedType": {
                "text": "'foo' | 'bar' | 'baz' | "
              }
            },
            {
              "kind": "field",
              "name": "value5",
              "type": {
                "text": "Type2 | undefined"
              },
              "privacy": "private",
              "description": "Value 5 References.",
              "expandedType": {
                "text": "'foo' | 'bar' | 'baz' |  | undefined"
              }
            }
          ],
          "superclass": {
            "name": "LitElement",
            "package": "lit"
          },
          "tagName": "my-test",
          "customElement": true
        }
      ],
      "exports": [
        {
          "kind": "js",
          "name": "Test",
          "declaration": {
            "name": "Test",
            "module": "src/Test.ts"
          }
        },
        {
          "kind": "custom-element-definition",
          "name": "my-test",
          "declaration": {
            "name": "Test",
            "module": "src/Test.ts"
          }
        }
      ]
    }
  ]
}
```

`Value1` and `Value2` field got the correct expectation, but both `Value3` and `Value4` field show extra empty string, and `Value5` field show undefined, but still have empty string

**Comment by break-stuff** [comment]
If you make the property optional (`private value1?: Type1;`), does that fix it? I think the CEM Analyzer is trying to prevent issues for you if the the property is not optional.

**Comment by break-stuff** [comment]
I just deployed v1.1.4. This should resolve this issue. Let me know if you run into any problems.

**Comment by break-stuff** [comment]
Closing this for now. Let me know if there is anything else that comes up.

**Comment by Diaan** [comment]
I think I found a related/similar issue; When a property is optional (and can be `undefined`) the generation doesn't work when the declaration of the type is in a different file than the property.

button.ts:
```ts
export type ButtonSize = 'sm' | 'md' | 'lg';

@property({ reflect: true }) size?: ButtonSize;
```
generated model:
```json
"type": {
  "text": "ButtonSize | undefined"
},
"expandedType": {
  "text": "'sm' | 'md' | 'lg' | undefined"
}
```

When the type is in a separate file, but the property isn't optional:
models.ts:
```ts
export type ButtonSize = 'sm' | 'md' | 'lg';
```

button.ts"
```ts
import type { ButtonSize } from './models.js';

@property({ reflect: true }) size: ButtonSize = 'md';
```

generated model:
```json
"type": {
  "text": "ButtonSize"
},
"expandedType": {
  "text": "'sm' | 'md' | 'lg'"
}
```
the above example both work correctly, but the below (optional property and type in a separate file) doesn't:

models.ts:
```ts
export type ButtonSize = 'sm' | 'md' | 'lg';
```

button.ts:
```ts
import type { ButtonSize } from './models.js';

@property({ reflect: true }) size?: ButtonSize;
```

Generated model:
```json
"type": {
    "text": "ButtonSize | undefined"
  },
```
And no `expandedType`

**Comment by Diaan** [comment]
Yes, I installed it this week. I'm using `cem-plugin-expanded-types": "^1.1.4` 
The weird thing is it only happens when the type declaration is outside the current file. I've been digging in your code a bit and as far as I could see the types were not added to `aliasTypes` under the correct filename (button.js in this case)

**Comment by break-stuff** [comment]
Do you have a repro available that I can look at? If not, I can try to reproduce it

**Comment by Diaan** [comment]
I don't really have a small scenario with the exact problem, but the project i'm working on is open source, so if you want you can dive into it: https://github.com/sl-design-system/components

What happens in the project (a Design System) is that when the components get build a `custom-elements.json` file is generated for each component. These custom elements are then later, in the build for the documentation website aggregated in 1 big file. That is also where the ExpandedType filter is run.

The specific problem is with [Checkbox Group](https://github.com/sl-design-system/components/blob/fix/generate-website-files/packages/components/checkbox/src/checkbox-group.ts), here the property `size` of type CheckboxSize is optional and the possible values of `CheckboxSize` don't get resolved.

In [Checkbox](https://github.com/sl-design-system/components/blob/fix/generate-website-files/packages/components/checkbox/src/checkbox.ts) however, the `CheckboxSize` isn't optional and gets resolved.

I think it's a combination of the fact that a property is optional and where the type is defined (in the same file as where the variable uses the type or not)

Some other files that may be relevant:
- [custom-elements-manifest.config.js](https://github.com/sl-design-system/components/blob/fix/generate-website-files/website/custom-elements-manifest.config.js)
- [Generated custom-elements.json](https://github.com/sl-design-system/components/blob/fix/generate-website-files/website/src/_data/custom-elements/custom-elements.json)

If you need more information or help finding specific files/ settings let me know

**Comment by break-stuff** [comment]
Thank you! I'll dig into this and let you know what I find.

**Comment by certainlyakey** [comment]
We've got a similar issue (in a Stencil-based library) where `expandedType` works for a type defined inside of the component file; it stops working when the type is moved outside, with no regard to prop being optional or not.

I will try to create a repro and create a separate issue.

**Comment by break-stuff** [comment]
Thank you for your patience! Release 1.2.0 should resolve this issue.

**Comment by certainlyakey** [comment]
Hmm the 1.2.0 still didn't solve the issue for me. But i'll try and setup an example repo as promised.

**Comment by break-stuff** [comment]
It looks like this issue was solved by including the file with the types in the CEM Analyzer `globs` property.
